---
- hosts: all

  pre_tasks:
    - name: Ensure cron is installed, otherwise tests will fail | Redhat
      package:
        name: cronie
        state: present
      when: ansible_os_family == 'RedHat'
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2

    - name: Ensure cron is installed, otherwise tests will fail | Debian / Ubuntu
      package:
        name: cron
        state: present
      when: ansible_os_family == 'Debian'
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2

  roles:
    - role: jgeusebroek.sysstat
